In [65]:
import numpy as np
from sklearn.datasets import load_iris
# load data
iris=load_iris()
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [24]:
features=iris.data.T
# mean
miu=np.array([np.mean(features[0]),np.mean(features[1]),np.mean(features[2]),np.mean(features[3])])
miu

array([5.84333333, 3.05733333, 3.758     , 1.19933333])

In [3]:
# K1  homogeneous quadratic kernel matrix
K1=np.zeros((150,150))
for i in range(len(iris.data)):
    for j in range(len(iris.data)):
        K1[i][j]=np.dot(iris.data[i],iris.data[j])
K1

array([[40.26, 37.49, 37.03, ..., 51.33, 51.54, 48.09],
       [37.49, 35.01, 34.49, ..., 48.53, 48.6 , 45.41],
       [37.03, 34.49, 34.06, ..., 47.31, 47.5 , 44.32],
       ...,
       [51.33, 48.53, 47.31, ..., 82.29, 83.18, 77.47],
       [51.54, 48.6 , 47.5 , ..., 83.18, 84.45, 78.46],
       [48.09, 45.41, 44.32, ..., 77.47, 78.46, 73.06]])

In [4]:
# K2 centered kernel matrix
m1=np.identity(150)
m2=np.ones((150,150))/150
m3=m1-m2
K2=np.dot(np.dot(m3,K1),m3)
K2

array([[ 7.30732933,  7.23466267,  7.70766267, ..., -4.71387067,
        -5.085204  , -3.832204  ],
       [ 7.23466267,  7.451996  ,  7.864996  , ..., -4.81653733,
        -5.32787067, -3.81487067],
       [ 7.70766267,  7.864996  ,  8.367996  , ..., -5.10353733,
        -5.49487067, -3.97187067],
       ...,
       [-4.71387067, -4.81653733, -5.10353733, ...,  3.15492933,
         3.463596  ,  2.456596  ],
       [-5.085204  , -5.32787067, -5.49487067, ...,  3.463596  ,
         4.15226267,  2.86526267],
       [-3.832204  , -3.81487067, -3.97187067, ...,  2.456596  ,
         2.86526267,  2.16826267]])

In [5]:
# K3 normalized kernel matrix
m4=np.eye(150,k=0)
for i in range(150):
    m4[i][i]=K2[i][i]**(-1/2)
K3=np.dot(np.dot(m4,K2),m4)
K3

array([[ 1.        ,  0.9803985 ,  0.98567247, ..., -0.98175586,
        -0.92318052, -0.96274957],
       [ 0.9803985 ,  1.        ,  0.99598195, ..., -0.99335345,
        -0.95780028, -0.94904666],
       [ 0.98567247,  0.99598195,  1.        , ..., -0.9932664 ,
        -0.93218977, -0.93245616],
       ...,
       [-0.98175586, -0.99335345, -0.9932664 , ...,  1.        ,
         0.95695166,  0.93925383],
       [-0.92318052, -0.95780028, -0.93218977, ...,  0.95695166,
         1.        ,  0.95491801],
       [-0.96274957, -0.94904666, -0.93245616, ...,  0.93925383,
         0.95491801,  1.        ]])

In [63]:
iris.data[0]

array([-17.30777778,  -8.547     , -11.20620339,  -3.55633333])

In [66]:
# Verify
#中心化
m5=iris.data
for i in range(150):
    m5[i]=iris.data[i]-miu    
m6=np.zeros((150,150))
for i in range(150):
    for j in range(150):
        m6[i][j]=np.dot(m5[i],m5[j])
m6

array([[ 7.30732933,  7.23466267,  7.70766267, ..., -4.71387067,
        -5.085204  , -3.832204  ],
       [ 7.23466267,  7.451996  ,  7.864996  , ..., -4.81653733,
        -5.32787067, -3.81487067],
       [ 7.70766267,  7.864996  ,  8.367996  , ..., -5.10353733,
        -5.49487067, -3.97187067],
       ...,
       [-4.71387067, -4.81653733, -5.10353733, ...,  3.15492933,
         3.463596  ,  2.456596  ],
       [-5.085204  , -5.32787067, -5.49487067, ...,  3.463596  ,
         4.15226267,  2.86526267],
       [-3.832204  , -3.81487067, -3.97187067, ...,  2.456596  ,
         2.86526267,  2.16826267]])

In [67]:
# 归一化
m7=m5
for i in range(150):
    m7[i]=m5[i]/np.linalg.norm(m5[i])
m8=np.zeros((150,150))
for i in range(150):
    for j in range(150):
        m8[i][j]=np.dot(m7[i],m7[j])
m8

array([[ 1.        ,  0.9803985 ,  0.98567247, ..., -0.98175586,
        -0.92318052, -0.96274957],
       [ 0.9803985 ,  1.        ,  0.99598195, ..., -0.99335345,
        -0.95780028, -0.94904666],
       [ 0.98567247,  0.99598195,  1.        , ..., -0.9932664 ,
        -0.93218977, -0.93245616],
       ...,
       [-0.98175586, -0.99335345, -0.9932664 , ...,  1.        ,
         0.95695166,  0.93925383],
       [-0.92318052, -0.95780028, -0.93218977, ...,  0.95695166,
         1.        ,  0.95491801],
       [-0.96274957, -0.94904666, -0.93245616, ...,  0.93925383,
         0.95491801,  1.        ]])